apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poe-frontend
  labels:
    app: poe-frontend
spec:
  selector:
    matchLabels:
      app: poe-frontend
      tier: web
  template:
    metadata:
      labels:
        app: poe-frontend
        tier: web
        sha: ${SHORT_SHA}
    spec:
      containers:
      - name: poe-frontend
        image: gcr.io/website-227817/poe-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: poe-frontend
  labels:
    app: poe-frontend
spec:
  type: NodePort
  selector:
    app: poe-frontend
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poe-frontend
  annotations:
    kubernetes.io/ingress.global-static-ip-name: website-ip
  labels:
    app: poe-frontend
spec:
  backend:
    serviceName: poe-frontend
    servicePort: 8080